### ISSUE TITLE
Some reformation logs being sent in #teachers-lounge instead of #reformation-logs

### ISSUE THREAD

**Issue by gombik42** [Yoshod/Sersi#101]
- ~~[ ] reformation channel transcripts should be sent into #reformation-logs~~
one of these is wrong:
- [ ] reformation failed posted only in #teachers-lounge
- [ ] sucessful reformation posted in both channels

**Comment by Yoshod** [comment]
Reformation transcripts going to teachers lounge and not the public logs is intentional behaviour

**Comment by Yoshod** [comment]
Reformation failed should go both to teachers lounge and public moderation logs but should not disclose who the moderators who voted are, or their reasons. Should also not include a transcript.
