### ISSUE TITLE
Anti-Tamper Not Activating

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#121]
Anti-tamper appears to be busted, have tried deleting logs and no alerts are raised.

**Comment by Yoshod** [comment]
When deleting a message comprised of text the audit log datetime check results in the deletion being ignored.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/10157815/194907035-fc5dd15a-4264-4bfd-af26-5849b2746ccb.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/10157815/194907105-1f1a61e1-fa97-4d4d-83b2-c32573bec42c.png">

**Comment by Yoshod** [comment]
The above does not trigger **at all** with embed only logs.

**Comment by Yoshod** [comment]
It appears that deleting an embed only message does not trigger on_message_delete at all.

**Comment by kisachi5** [comment]
Might be because they are webhook integrations, and not you typical messages. Oh dear.

**Comment by Yoshod** [comment]
> Might be because they are webhook integrations, and not you typical messages. Oh dear.

This also happens for Sersi logs which iirc are actual messages.

**Comment by kisachi5** [comment]
now works with both webhook and bot messages, will fetch embeds, and display content
