### ISSUE TITLE
Alert Tracking

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#136]
When an alert is created the following should be tracked:
- [ ] Alert type
- [ ] Creation time

When an alert is responded to the track should be updated with:
- [ ] Time responded to

This information should be exported to a CSV by using s!response_export

**Comment by kisachi5** [comment]
Why a CSV? Other filetypes might be more useful for that

**Comment by Yoshod** [comment]
Because it's just something quick and dirty I need for a week or so. Can look at improving it later.

**Comment by Yoshod** [comment]
> Why a CSV? Other filetypes might be more useful for that

Also because I'm opening the file straight into a spreadsheet editor to do stuff with the data manually. So a CSV is the best file format for that afaik.

**Comment by kisachi5** [comment]
[540800f](https://github.com/Yoshod/Sersi/commit/540800f897b34484b5c534b8a37473abf4a38981) done
