### ISSUE TITLE
Rewrite Old Commands as Slash Commands

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#139]
Currently there are 61 old style commands:

- [ ] Adult Access Embed
- [x] Adult Access Revoke
- [x] Nevermod
- [x] UwU
- [x] Coinflip
- [x] DM
- [ ] Mass Move
- [x] Archive
- [x] Config Set
- [x] Reload Bot
- [x] Config
- [x] Don't Ask to Ask
- [ ] Mod Apps
- [ ] Staff Info
- [ ] CET Apps
- [x] Ban Appeal Embed
- [x] Blacklist User
- [x] List Blacklisted Users
- [x] Remove from Blacklist
- [x] Check Blacklist
- [ ] Set Caps Length
- [ ] Get Caps Length
- [x] User Cases
- [x] Gif Blacklist Add
- [x] Gif Blacklist Remove
- [x] Gif Blacklist View
- [x] Add ticket support
- [x] Remove ticket support
- [x] Add trial moderator
- [x] Make full moderator
- [x] Remove from moderator
- [x] Retire from staff
- [x] Feedback post
- [x] Perspective Investigate
- [x] Add to probation
- [x] Remove from probation
- [x] Purge
- [x] Timed Purge
- [x] Purge Until
- [x] Add to reformation
- [x] Reformation query
- [x] Reformation failed
- [ ] ~~Reformation case~~
- [x] Add slur
- [x] Add goodword
- [x] Remove slur
- [x] Remove goodword
- [x] List slurs
- [x] List goodwords
- [x] Suggest
- [ ] Mod Ticket Embed
- [x] Verification Ticket Embed
- [x] Timeout Appeal
- [x] Watchlist Add
- [x] List Watchlist
- [x] Remove from Watchlist
- [x] Check Watchlist

**Comment by kisachi5** [comment]
marked a bunch of removed (unused) commands as done, we will not be having them in v5

**Comment by Yoshod** [comment]
Only remaining command is mass move. Making that a Version 5.1.0 issue.
