### ISSUE TITLE
markdown prevention bug

### ISSUE THREAD

**Issue by lolarobins** [Yoshod/Sersi#148]
`>>> #` circumvents header markdown prevention as found out in general chat

as for the ppl there for it in chat i genuinely didn't understand that circumvention of headers was the bots intent since my messages passed through fine, it was post warn and the confusing spiel that followed that kinda made me realize that is what's going on

**Comment by kisachi5** [comment]
fixed in 5bba9ace4a46c71cfef1a368d41985d212e2802a, will be deployed with version 5
