### ISSUE TITLE
Leveling System

### ISSUE THREAD

**Issue by gombik42** [Yoshod/Sersi#152]
suggested levels:

```
Level 10 - Certified SUV Disliker
Level 09 - Train Simulator Addict
Level 08 - Metro Tunneller
Level 07 - Urban Mobility Advocate
Level 06 - Sustainable Transport Enthusiast
Level 05 - Trolleybus Wire Deployer
Level 04 - Rail Nationalisation Expert
Level 03 - Tram Extension Fan
Level 02 - Pedestrian Zone Enjoyer
Level 01 - Bicycle Path Fanatic
Level 00 - Newbie
```

**Comment by Yoshod** [comment]
Perhaps this is worth looking into https://github.com/krishsharma0413/DiscordLevelingCard

**Comment by Yoshod** [comment]
What we would need to determine:
- [x] How much XP is required for each role
- [x] How much XP do you gain per message
- [x] What is the cooldown between XP gains
- [x] Should perhaps longer messages beget more XP
- [x] Could we maybe do something with XP per minute spent in a VC
- [x] Do we do a big migration from Tatsu, no migration, or soft migrate a user the first time they send a message and have no XP with Sersi
