### ISSUE TITLE
Log messages from a channel upon channel deletion

### ISSUE THREAD

**Issue by kisachi5** [Yoshod/Sersi#161]
![grafik](https://github.com/Yoshod/Sersi/assets/76996779/8caac81c-4be2-4f18-8fb8-79f0c48c1201)

patreon logger can do it, so can we

**Comment by Yoshod** [comment]
So had a look around on the Patron Logger discord bot and the way this is implemented is via caching the last 48hrs of messages in a database. Not sure how I feel about this re: potential GDPR issues.

**Comment by Yoshod** [comment]
Due to potential concerns around GDPR will not be implementing this unless a way can be found that doesn't require us to cache messages.
