### ISSUE TITLE
Adult Access Blacklist

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#171]
**Description**:
When removing a person's access to the adult only channels, this should blacklist them from applying again for access.

**Use Case**:
If a person has been removed from the channel and presses the button to re-apply the bot should refuse to submit an application.

**Proposed Solution**:
I think this should be handled as a type of Case similar to slur usage or bad faith moderation ping. This would help keep easier track.

**Impact on Project**:
Could require changes to the Sersi database and config.

**Priority**:
Minor Feature

**Reason for Priority**:
Using the existing framework for interacting with the case system this shouldn't be too hard or time intensive to implement.

**Milestone**:
If we can fit this into 5.1.0 that would be ideal but depends on availability for more issues.

**Comment by gombik42** [comment]
as long as database changes only involve adding more tables they can be considered minor, if we need a change to existing tables we will need to implement a database migration system, which would be a major feature. adding a new case type should be the former

**Comment by gombik42** [comment]
also adult access requests could display (warn) cases related to posting NSFW imagery
