### ISSUE TITLE
Add ModMail Support to Tickets

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#213]
**Description**:
We should add a ModMail/StaffMail system to tickets so that users who are timed out can open a ticket to discuss their timeout. Would work better than an appeals system imo and is better for quality control than DMs.

**Use Case**:
A user who has been timed out would be able to start a ModMail chat with the mod team to appeal their timeout.

**Impact on Project**:
Potentially could see spam, as such we would need to implement rate limiting and blacklisting.

**Priority**:
Minor

**Milestone**:
5.2.0

**Comment by gombik42** [comment]
rate limiting is achieved via using slowmode on the ticket, users who are timed out can only create an Appeal ticket
