### ISSUE TITLE
Handle Unexpected User Idiocy

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#232]
The following situations are not accounted for in Sersi and need to be handled:

- [x] Timeouts removed through means other than Sersi
- [x] Alerts are deleted before ever being responded to
- [x] Suggestion management embed is deleted before being marked as completed or not happening
- [x] Suggestion embed is deleted before marked as completed or not happening
- [x] A voting embed is deleted before the vote concludes
- [x] Peer review embed is deleted before being approved or objected
- [x] Ticket is closed via deleting the channel itself
- [x] Make ticket category/subcategory setting on close more user friendly

**Comment by Yoshod** [comment]
Suggestions handled in c0baf45

If a suggestion panel is deleted it can be recalled via a new command using the Suggestion ID.

If a suggestion itself is deleted, the panel is closed and the suggestion is considered to be Not Happening.

**Comment by gombik42** [comment]
[0287a09](https://github.com/Yoshod/Sersi/commit/0287a099be49bd443cabb91549fa2638b36e41be) if someone deletes an ongoing vote, it gets reposted

**Comment by Yoshod** [comment]
Timeouts handled in 08b7604

If a timeout is added not through Sersi a case is generated and an alert sent.

If a timeout is removed not through Sersi the timeout case is updated and an alert sent.

**Comment by gombik42** [comment]
[45945be](https://github.com/Yoshod/Sersi/commit/45945bea1ad00d0719527fe777abfdcef3a1592e) relevant staff is alerted when a ticket is deleted without being closed via the close command

**Comment by Yoshod** [comment]
4bf1c21 deleted alerts are now reposted

**Comment by gombik42** [comment]
[c80ca70](https://github.com/Yoshod/Sersi/commit/c80ca70ae3bafccbfcd8ccaa42e6b6bb9d18a0f9) users will now be prompted to give the ticket (sub)category via message dialogue

**Comment by gombik42** [comment]
@Yoshod let's leave this open until 5.2.2 release in case we come up with more

**Comment by Yoshod** [comment]
4280978 Implemented a new slash command to allow for reviewing a case based off of its ID
