### ISSUE TITLE
XP Boost for Server Boosters

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#241]
**Description**:
Give an XP boost for users who boost the server.

**Use Case**:
To increase Server Boosters.

**Proposed Solution**:
Could either be a flat extra XP or could be done as a % modifier.

**Impact on Project**:
Low Impact

**Priority**:
Minor

**Reason for Priority**:
Should be a simple implementation but I'm unsure.

**Milestone**:
5.2.3

**Comment by gombik42** [comment]
could be implemented as treating certain roles as an xp multiplier

**Comment by Yoshod** [comment]
Implemented in a2001ac
