### ISSUE TITLE
Sticky Roles

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#244]
**Description**:
When a user leaves the server, keep a track of their roles for 28 days. If they rejoin within 28 days give them the roles back (with the exception of staff roles).

**Use Case**:
For when a user leaves and rejoins.

**Proposed Solution**:
Track this in the Sersi DB.

**Additional Context**:
Routinely check the DB once every 24hrs to remove data from users over 28 days.

**Priority**:
Minor

**Reason for Priority**:
Should be a simple implementation.

**Milestone**:
5.2.3

**Comment by gombik42** [comment]
we have the `misc.roles` cog, which would be perfect place for this

**Comment by Yoshod** [comment]
Implemented in 2278e7b
