### ISSUE TITLE
Bug Report: No VC Leave Logs

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#246]
**Description:**
When a user joins or leaves a VC this is logged by Sersi. Except for some reason leaving VC isn’t getting logged.

**Steps to Reproduce:**
Join a VC, then leave it.

**Expected Behaviour:**
There would be a VC left log.

**Screenshots:**
Must be uploaded manually.

**Client Type:**
mobile

**Client Version:**
stable

**Additional Info:**
None

**This issue was submitted automatically by Sersi.**

**Comment by gombik42** [comment]
voice disconnect logs now show
