### ISSUE TITLE
Errors that should be personalised

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#66]
- [ ] blacklistuser (no args provided)
- [ ] checkblacklist (no args provided)
- [ ] removefromblacklist (no args provided)
- [ ] setcapslength (no args provided)
- [ ] addgif (no args provided)
- [ ] removegif (no args provided)
- [ ] nevermod (no args provided)
- [ ] addticketsupport (no args provided)
- [ ] addtrialmod (no args provided)
- [ ] makefullmod (no args provided)
- [ ] removefrommod (no args provided)
- [ ] addprobation (no args provided)
- [ ] removeprobation (no args provided)
- [ ] purge (no args provided)
- [ ] purge_until (no args provided)
- [ ] timed_purge (no args provided)
- [ ] reformationfailed (no args provided)
- [ ] reformationneeded (no args provided)
- [ ] reformationquery (no args provided)
- [ ] addgoodword (no args provided)
- [ ] addslur (no args provided)
- [ ] removegoodword (no args provided)
- [ ] removeslur (no args provided)
- [ ] massmove (no args provided)
- [ ] checkwatchlist (no args provided)
- [ ] removefromwatchlist (no args provided)
- [ ] watchlistuser (no args provided)

**Comment by kisachi5** [comment]
will be unnecessary with move to slash commands
