### ISSUE TITLE
Prevent Certain Users from Sending Anonymous Messages

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#91]
- [x] Banned users
- [x] Muted users
- [x] Reformation users

should not be able to send anonymous messages.

**Comment by kisachi5** [comment]
banned users already can't send messages due to no mutual server with sersi, unless they are in the appeals server.

**Comment by Yoshod** [comment]
> banned users already can't send messages due to no mutual server with sersi, unless they are in the appeals server.

The appeals server is what I was referring to
