### ISSUE TITLE
Sersi Logging System

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#94]
The following should be logged:
**Channel Logs**
- [x] Channel Created
- [x] Channel Updated
- [x] Channel Deleted

**Role Changes**
- [x] Role Created
- [x] Role Updated
- [x] Role Deleted

**Messages**
- [x] Message Deleted
- [x] Message Bulk Deleted
- [x] Message Updated

**Join Leave**
- [x] Member Join
- [x] Member Leave

**Members**
- [x] Role Assigned
- [x] Role Removed
- [x] Avatar Updated
- [x] Name Updated

**Guild Changes**
- [x] Guild Name Changed
- [x] Guild vanity url changed
- [x] Emoji Added
- [x] Emoji Removed
- [x] Emoji Updated

Message deleted/edited should say if the message which has been deleted/edited contained a slur.

**Comment by kisachi5** [comment]
in order to properly work on this, can @sersi_contributor get viewing access to the logging channels?

**Comment by kisachi5** [comment]
da9c8b23 done
