### ISSUE TITLE
Politics and Debate Mute

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#96]
A command which assigns a user a role set to deny users the ability to post in politics or debate. Perhaps s!badfaith or the like. Should require a reason.

**Comment by kisachi5** [comment]
Isn't there already an "annoying" or "bad ideas" role like that?

Should there also be a command to take away the role?

**Comment by Yoshod** [comment]
> Isn't there already an "annoying" or "bad ideas" role like that?
> 
> 
> 
> Should there also be a command to take away the role?

We have roles like that for other things (vc and so on) but not for politics and debate. Also, yeah a command to remove it as well.

**Comment by kisachi5** [comment]
at this point, it (in my opinion) makes more sense to have a single functionality for all those roles (probation, badfaith etc.)
commands stay the same, however the internal routines are amalgomated

**Comment by Yoshod** [comment]
> at this point, it (in my opinion) makes more sense to have a single functionality for all those roles (probation, badfaith etc.)
> 
> commands stay the same, however the internal routines are amalgomated

Something like:
s!punish @ Person punishment reason

**Comment by kisachi5** [comment]
wait, i just noticed the politically cucked role is exactly that

**Comment by Yoshod** [comment]
No longer planned
