### ISSUE TITLE
Ignored Channels

### ISSUE THREAD

**Issue by Yoshod** [Yoshod/Sersi#97]
Create a s!ignore and s!removeignore (and appropriate aliases) command which will add a channel ID to a list which Sersi checks when responding to pings and slurs. If channel is in list then do not respond.

Tickets should automatically be ignored

**Comment by gombik42** [comment]
added ignoring pings in tickets as part of the issue

**Comment by Yoshod** [comment]
Will delay this feature to 5.2.0 to see how #158 interacts with the slur and ping systems

**Comment by gombik42** [comment]
we have ignored categories and channels in config, should just make sure it is used where necessary

**Comment by gombik42** [comment]
pretty sure we already have this implemented with ignored_categories and ignored_channels in config
